apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  GITHUB_APP_ID: "{{ .Values.config.githubAppId }}"
  AZURE_OPENAI_ENDPOINT: "{{ .Values.config.azureOpenAiEndpoint }}"
  AZURE_OPENAI_DEPLOYMENT: "{{ .Values.config.azureOpenAiDeployment }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.config.azureOpenAiApiVersion }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  ENVIRONMENT: "{{ .Values.config.environment }}"
  AGENT_MODE: "{{ .Values.agentMode }}"
  AGP_GATEWAY_ENDPOINT: "{{ .Values.agpGatewayEndpoint }}"
