  GPT_DEPLOYMENT_NAME: # THE GPT DEPLOYMENT NAME.
  AZURE_OPENAI_API_KEY: # THE GPT DEPLOYMENT KEY.
  AZURE_OPENAI_ENDPOINT: # THE GPT DEPLOYMENT ENDPOINT.
  code_dir: # The dataset folder eg: dataset
  outer_folder_path: # The outer folder in dataset eg: pr_data_latest
  alfred_comments_json: # The alfred comments json file eg:anusha-1209_cisco-eti-prreplay.json 
  repo_name: # The repo name eg: Anusha-1209/Cisco-ETI-PRReplay
  rating_file_path: # The rating file path eg: dataset/rating_new_both.json
  except_file_path: # The exceptions file path eg: dataset/except_file_path.json
  error_file_path: # The error file path eg: dataset/error_file_path.json