github_token: # REPLACE WITH YOUR GITHUB TOKEN
repo_name: # REPLACE WITH GITHUB REPO WHERE PR REPLAY RUNS
pr_directory_path: # REPLACE FILE PATH WHICH HAS BASE AND CHANGED CODE FOR ALL PR's
metadata_file: #REPLACE WITH FILE THAT CONTAINS INFORMATION ABOUT LIST OF PR's AND COMMIT
pr_to_run: # [REPLACE WITH LIST OF PR NUMBERS TO IT IS ALL LEAVE IT AS EMPTY LIST]