github_token: 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
repo_name: Anusha-1209/Cisco-ETI-PRReplay
pr_directory_path:  cisco-eti-platform-dataset/dataset/pr_data_latest/cisco-eti/platform-terraform-infra
metadata_file: dataset/cisco-eti_platform-terraform-infra.json
pr_to_run: []