FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

RUN dnf update -y && \
    dnf install -y \
    unzip \
    jq \
    ca-certificates && \
    dnf clean all

# Install Terraform, Alfred will run static analyzers on the repo
RUN curl -Lo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.6.1/terraform_1.6.1_linux_amd64.zip && \
    unzip /tmp/terraform.zip -d /usr/local/bin/ && \
    rm -f /tmp/terraform.zip

# Install tflint for the same reasons as above
RUN curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

# Build Alfred
COPY ./src/ .
COPY pyproject.toml .
COPY poetry.lock .

RUN pip install poetry
# We don't need a virtual env, the image itself is an isolated env
RUN poetry config virtualenvs.create false 
RUN poetry install --only main

CMD [ "main.handle_event" ]