FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY ./src/ .
COPY pyproject.toml .
COPY poetry.lock .

RUN pip install poetry
# We don't need a virtual env, the image itself is an isolated env
RUN poetry config virtualenvs.create false 
RUN poetry install --no-dev

CMD [ "main.handle_event" ]