data_path2: dataset/data.json
output_append: _labeled 
local_dir: dataset/pr_data_latest/Azure/terraform/
data_path: dataset/azure_terraform.json
local_dir2: dataset/pr_data_latest/data/
subfolder_base: base_file/
subfolder_change: final_merged_file/
api_version: 2023-05-15
AZURE_OPENAI_ENDPOINT: AZURE_OPENAI_ENDPOINT
AZURE_OPENAI_API_KEY: AZURE_OPENAI_API_KEY