name: Build and Push Python Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pull-and-push:
    runs-on: ubuntu

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        no-cache: true
        tags: ghcr.io/${{ github.repository_owner }}/alfred:latest