name: helm push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  chart:
    name: Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Simplified to latest stable version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v4 # Simplified to latest stable version
        with:
          version: "3.12.1" # Default Helm version

      - name: Helm lint
        run: helm lint charts/prcoach --with-subcharts

      - name: Package and Push Helm Chart
        env:
          CHART_VERSION: "1.0.0" # Replace with a valid SemVer version
        run: |
          helm package charts/prcoach --dependency-update --version $CHART_VERSION
          helm push prcoach-$CHART_VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/helm
