name: Pull and Push Python Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pull-and-push:
    runs-on: ubuntu

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull image from public ECR
      run: |
        docker pull public.ecr.aws/lambda/python:3.12

    - name: Tag the image for GHCR
      run: |
        docker tag public.ecr.aws/lambda/python:3.12 ghcr.io/${{ github.repository_owner }}/lambda/python:3.12.9

    - name: Push image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/lambda/python:3.12.9 
